<html>
	<head>
		<title>Bienvenid@</title>
	</head>
<body>
<h3>Bienvenid@ al registro para el intercambio </h3>
<p>
Antes de continuar con el registro es necesario que tomes en cuenta lo siguiente:<br/>
<br/>
<br/>
El correo que proporciones te servira para recibir la notificacion de la persona a la que te toco regalarle asi como tambien aparecera la lista 
con las sugerencias que te hace para el regalo, por lo tanto pon un correo que revises frecuentemente. <br/>
<br/>
En la primer pagina existe un campo llamado relacion, este es para poner si es primo, tio, sobrino, pato y vuela lo que quieras pero nos servira 
por aquellos que estan fuera del planeta y no nos conocen, osea por si alguien no te identifica pueda conocer que eres hij@ de perenganita o sutanito o esposo, asi que ese campo es libre. <br/>
<br/>
Una vez que te hayas registrado como primo se mandara a una pagina en la cual se te pedira que escribas las sugerencias del regalo, 
recuerda que tambien tu leeras una lista  como la que estas escribiendo por lo tanto da tantas ideas como puedas, no importa que creas que 
es santa, tu pide como si deverdad te lo fueran a regalar solo te recuerdo que el precio minimo es de 250 pesos ya si tu corazon y bolsillo da mas
no seas tacaño :P es navidad y puedes derrochar en el regalo. Dios lo vera como una seña de despojo al materialismo. 
<br/>
si tienes algun problema o necesitas ayuda para tu registro mandame un correo a arkais@gmail.com para ayudarte.
si ya te registraste una vez y quieres cambiar tu lista mandame un correo para borrar tu registro y asi no existan registros de mas. <br/>
<br/>
<br/>
Una vez que todos los usuarios esten registrados o se cumpla el tiempo del registro el sistema realizara una seleccion aleatoria de las personas que estan en la bd 
<br/>
y enviara un correo a las participantes la persona y la lista de sugerencias .
</p>
 <a href="<?php echo $this->url(
            array('controller'=>'sign'),
            'default',
            true) ?>">Registrarse</a>
</body>
</html>