<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Granaditos Gift Exchane</title>
  <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Granadito's Gift Exchange</b>
    </div>
    <div id="header-navigation" style="float: right">
      
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>